urls:
  - "http://feeds.feedburner.com/AeonMagazineEssays?format=xml"
  - http://feeds.feedburner.com/Metafilter  
  - http://feeds.feedburner.com/fastcompany/headlines
  - http://www.newyorker.com/services/rss/feeds/everything.xml
  - http://economix.blogs.nytimes.com/feed/
  - http://allthingsd.com/feed/
  - http://www.fastcodesign.com/rss.xml
  - http://feeds.feedburner.com/RSSMicro/Top_News
  - http://www.google.com/trends/hottrends/atom/hourly
  - http://bits.blogs.nytimes.com/feed/
  - http://feeds.pinboard.in/rss/popular/wikipedia/
  - http://feeds.pinboard.in/rss/recent/
  - "http://en.wikipedia.org/w/api.php?action=featuredfeed&feed=featured&feedformat=atom"
  - http://waxy.org/links/index.xml
  - http://rss.cnn.com/rss/edition.rss
  - http://feeds.feedburner.com/flavorwire-rss
  - http://www.collaborativeconsumption.com/atom.xml
  - "http://news.google.com/news?pz=1&cf=all&ned=uk&hl=en&topic=h&num=3&output=rss"
  - http://www.edidomus.it/ed/feedyn/feed.cfm?name=domus_english
  - http://www.scottaaronson.com/blog/?feed=rss2
  - http://feeds.ribbonfarm.com/Ribbonfarm?format=xml
  - http://www.ediblegeography.com/feed/
  - http://natgeofound.tumblr.com/rss
  - http://millionsmillions.tumblr.com/rss
  - http://www.amazon.com/rss/new-releases/books/10132?tag=themillions10-20
  - http://jasminatesanovic.wordpress.com/feed/
  - http://www.ultraculture.org/feed/
  - http://programmingisterrible.com/rss
  - http://blog.sironaconsulting.com/sironasays/rss.xml
  - http://www.futurist.com/feed/
  - http://stratechery.com/feed/
  - http://themindfulbit.com/feed
  - http://sellsellblog.blogspot.com/feeds/posts/default?alt=rss
  - http://feeds2.feedburner.com/subtraction
  - http://feeds.goodproductmanager.com/GoodProductManager
  - http://feeds.feedburner.com/TynerBlain
  - http://www.svproduct.com/articles/rss
  - http://feeds.feedburner.com/sachinrekhiblog
  - http://product-management.alltop.com/rss/
  - http://www.quora.com/rss
  - http://quoratopstories.tumblr.com/rss
  - http://feeds.feedburner.com/Christophercummingscom
  - http://feeds2.feedburner.com/ItProductManagement
  - http://feeds.feedburner.com/SpatiallyRelevant
