urls:
  - https://www.hackread.com/feed/
  - https://news.vice.com/rss
  - http://marginalrevolution.com/feed
  - https://interestingtalks.in/London/feed/
  - http://www.iht.com/feed/
  - http://rss.royalsociety.org/events/upcoming
  - "http://www.conflict-news.com/feed/"
  - http://feeds.feedburner.com/AtlanticInternational
  - http://www.aljazeera.com/xml/rss/all.xml
  - https://globalvoicesonline.org/feed/
  - http://www.newyorker.com/services/rss/feeds/everything.xml
  - http://www.google.com/trends/hottrends/atom/hourly
  - "https://en.wikipedia.org/w/api.php?action=featuredfeed&feed=featured&feedformat=atom"
  - http://breakingsmart.com/feed/
  - http://feeds.ribbonfarm.com/Ribbonfarm
  - http://feeds.pinboard.in/rss/popular/wikipedia/
  - http://feeds.feedburner.com/WikipediaTodaysFeaturedArticle
