urls:
  - http://feeds.feedburner.com/Metafilter  
  - http://feeds.feedburner.com/popurls
  - http://www.buzzfeed.com/index.xml
  - http://feeds.feedburner.com/fastcompany/headlines
  - http://feeds2.feedburner.com/PitchforkLatestNews
  - http://feeds2.feedburner.com/PitchforkFeatures
  - http://www.newyorker.com/services/rss/feeds/everything.xml
  - http://everything2.com/node/ticker/New+Writeups+Atom+Feed
  - http://www.postsecret.com/feeds/posts/default?alt=rss
  - http://feeds.feedburner.com/covermesongs
  - http://page2rss.com/0e695ef2955f51e39302ae11139b5981
  - http://www.thisiswhyimbroke.com/feed
  - http://tvtropes.org/pmwiki/rss.xml
  - http://feeds.feedburner.com/uproxx/filmdrunk
  - http://blog.okcupid.com/index.php/feed/
  - http://www.theverge.com/rss/index.xml
  - http://www.blogger.com/feeds/19336675/posts/default
  - http://economix.blogs.nytimes.com/feed/
  - http://feeds.feedburner.com/TheAtlantic
  - http://catalogliving.net/rss
  - http://allthingsd.com/feed/
  - http://page2rss.com/cdf1dd412d47809f138a65dd9c0498e8
  - http://page2rss.com/442f58bddbab6bf73eb98e5c261c4461
  - http://feeds.feedburner.com/bigthink/main
  - http://page2rss.com/82d1a3eaf37249bece1634d247f123d4
  - http://feeds2.feedburner.com/blogspot/summertomato
  - http://zenhabits.net/feed/
  - http://smarthistory.khanacademy.org/rss
  - http://dearphotograph.com/rss
  - http://wonderopolis.org/feed/
  - http://feeds.feedburner.com/getthefive/pWyz
  - http://feeds.feedburner.com/twistedsifter
  - http://feeds.feedburner.com/getaddictedto
  - http://feeds.feedburner.com/The99Percent
  - http://www.fastcodesign.com/rss.xml
  - http://feeds.feedburner.com/Venturebeat
  - http://www.freakonomics.com/feed/
  - http://page2rss.com/08886babbf589154f8fa3f914c46a805
  - http://feeds.feedburner.com/InterestingThingOfTheDay
  - http://feeds.feedburner.com/fbspin
  - http://hellogiggles.com/feed
  - http://www.aldaily.com/rss/rss.xml
  - http://feeds.feedburner.com/rhizome-fp
  - http://feeds2.feedburner.com/slashfilm
  - http://artdaily.org/rss.asp
  - http://feeds.feedburner.com/RSSMicro/Top_News
  - http://backend.deviantart.com/rss.xml?q=special%3Add
  - http://rss1.smashingmagazine.com/feed/
  - http://www.rssmicro.com/feeds/top-feeds.rss
  - http://www.google.com/trends/hottrends/atom/hourly
