urls:
  - http://feeds.feedburner.com/AtlanticInternational
  - http://rss.nytimes.com/services/xml/rss/nyt/InternationalHome.xml
  - http://www.aljazeera.com/xml/rss/all.xml
  - https://globalvoicesonline.org/feeds/
  - http://breakingsmart.com/feed/
  - http://www.newyorker.com/services/rss/feeds/everything.xml
  - http://economix.blogs.nytimes.com/feed/
  - http://www.google.com/trends/hottrends/atom/hourly
  - http://en.wikipedia.org/w/api.php?action=featuredfeed&feed=featured&feedformat=atom
  - http://natgeofound.tumblr.com/rss
  - http://www.saastr.com/feed/
  - http://feeds2.feedburner.com/TheAwl
