urls:
  - http://feeds.feedburner.com/Metafilter  
  - http://feeds.feedburner.com/fastcompany/headlines
  - http://www.newyorker.com/services/rss/feeds/everything.xml
  - http://everything2.com/node/ticker/New+Writeups+Atom+Feed
  - http://economix.blogs.nytimes.com/feed/
  - http://feeds.feedburner.com/TheAtlantic
  - http://allthingsd.com/feed/
  - http://feeds.feedburner.com/bigthink/main
  - http://smarthistory.khanacademy.org/rss
  - http://wonderopolis.org/feed/
  - http://www.fastcodesign.com/rss.xml
  - http://feeds.feedburner.com/Venturebeat
  - http://www.freakonomics.com/feed/
  - http://feeds.feedburner.com/InterestingThingOfTheDay
  - http://www.aldaily.com/rss/rss.xml
  - http://feeds.feedburner.com/rhizome-fp
  - http://artdaily.org/rss.asp
  - http://feeds.feedburner.com/RSSMicro/Top_News
  - http://www.google.com/trends/hottrends/atom/hourly
  - http://bits.blogs.nytimes.com/feed/
  - http://networkawesome.com/rss/shows
  - http://www.nowness.com/issue/syndicate?output=rss
  - http://feeds.pinboard.in/rss/popular/wikipedia/
  - http://waxy.org/links/index.xml
  - http://daringfireball.net/index.xml
  - http://rss.cnn.com/rss/edition.rss
  - http://feeds.feedburner.com/flavorwire-rss
  - http://www.collaborativeconsumption.com/atom.xml
  - http://www.theverge.com/rss/index.xml
  - http://www.thisispopularculture.com/feed/
  - http://news.google.com/news?pz=1&cf=all&ned=uk&hl=en&topic=h&num=3&output=rss
  - http://feeds.feedburner.com/devourfeed
  - http://mindtheproduct.com/feed/
