urls:
  - http://99percentinvisible.org/feed/
  - http://feeds.feedburner.com/ThingsMagazine
  - http://feeds.feedburner.com/LettersOfNote
  - http://thefeature.net/rss/links
  - http://raspberrypi.stackexchange.com/feeds
  - https://medium.com/feed/@EskoKilpi
  - https://www.youtube.com/feeds/videos.xml?channel_id=UCjFqcJQXGZ6T6sxyFB-5i6A
  - http://rss.slashdot.org/Slashdot/slashdotMain
  - https://www.hackread.com/feed/
  - https://news.vice.com/rss
  - http://marginalrevolution.com/feed
  - https://interestingtalks.in/London/feed/
  - http://www.iht.com/feed/
  - http://rss.royalsociety.org/events/upcoming
  - "http://www.conflict-news.com/feed/"
  - http://feeds.feedburner.com/AtlanticInternational
  - http://www.aljazeera.com/xml/rss/all.xml
  - https://globalvoicesonline.org/feed/
  - http://www.newyorker.com/services/rss/feeds/everything.xml
  - http://www.google.com/trends/hottrends/atom/hourly
  - "https://en.wikipedia.org/w/api.php?action=featuredfeed&feed=featured&feedformat=atom"
  - http://breakingsmart.com/feed/
  - http://feeds.ribbonfarm.com/Ribbonfarm
  - http://feeds.pinboard.in/rss/popular/wikipedia/
  - http://feeds.feedburner.com/typepad/dboyd/innovationinpractice
  - http://feeds.feedburner.com/fastcoexist/feed
  - http://www.boardofinnovation.com/feed/
  - http://scottbarrykaufman.com/feed/
  - http://www.creativitypost.com/site/feed
  - http://feeds.feedburner.com/alistapart/main
  - http://feeds.feedburner.com/InterestingThingOfTheDay
  - http://lithub.com/feed/
  - http://www.growlot.com/feed/
  - https://news.google.com/news?pz=1&cf=all&ned=uk&hl=en&output=rss
  - http://mf.feeds.reuters.com/reuters/UKVideoBreakingviews
  - http://feeds.reuters.com/Reuters/worldNews
  - http://www.dictionary.com/wordoftheday/wotd.rss
  - http://www.questionablecontent.net/QCRSS.xml
  - http://www.psychologytoday.com/collections/feed
  - http://www.quotationspage.com/data/qotd.rss
  - http://rss.sciam.com/ScientificAmerican-News
  - http://feeds.newscientist.com/science-news
  - http://peopleofdesign.ru/feed/
  - http://www.economist.com/rss/
  - http://www.businesswire.com/portal/site/home/rss/
  - http://hbswk.hbs.edu/rss.html
  - http://top25.sciencedirect.com/
  - http://www.rssmicro.com/feeds/top-feeds.rss
