urls:
  - "http://feeds.feedburner.com/AeonMagazineEssays?format=xml"
  - http://feeds.feedburner.com/Metafilter  
  - http://www.newyorker.com/services/rss/feeds/everything.xml
  - http://economix.blogs.nytimes.com/feed/
  - http://feeds.feedburner.com/RSSMicro/Top_News
  - http://www.google.com/trends/hottrends/atom/hourly
  - http://bits.blogs.nytimes.com/feed/
  - http://feeds.pinboard.in/rss/popular/wikipedia/
  - http://feeds.pinboard.in/rss/recent/
  - "http://en.wikipedia.org/w/api.php?action=featuredfeed&feed=featured&feedformat=atom"
  - http://waxy.org/links/index.xml
  - http://rss.cnn.com/rss/edition.rss
  - http://feeds.feedburner.com/flavorwire-rss
  - "http://news.google.com/news?pz=1&cf=all&ned=uk&hl=en&topic=h&num=3&output=rss"
  - http://www.edidomus.it/ed/feedyn/feed.cfm?name=domus_english
  - http://natgeofound.tumblr.com/rss
  - http://millionsmillions.tumblr.com/rss
  - http://www.amazon.com/rss/new-releases/books/10132?tag=themillions10-20
  - http://www.ultraculture.org/feed/
  - http://www.futurist.com/feed/
  - http://themindfulbit.com/feed
  - http://www.svproduct.com/articles/rss
  - http://quoratopstories.tumblr.com/rss
  - http://feeds.feedburner.com/BothSidesOfTheTable
  - http://blog.thefetch.com/feed/
  - http://www.instapaper.com/starred/rss/32456/bZWXYBxVKw54XVmkuyBJXrGf6zk
  - http://www.instapaper.com/rss/32456/aIqyeEjXO049bzmeiyg07YPGnY
  - http://www.feeddude.com/feeds/1038284433863214737.rss
  - http://feeds.feedburner.com/springwise/
  - http://we-make-money-not-art.com/rss.xml
  - http://documentarystorm.com/feed
  - http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/video-lectures/rss.xml
  - https://www.thebaffler.com/notebook/rss
  - http://stackexchange.com/feeds/questions
