urls:
  - "http://feeds.feedburner.com/AeonMagazineEssays?format=xml"
  - http://feeds2.feedburner.com/BpsResearchDigest
  - http://feeds.feedburner.com/Metafilter  
  - http://feeds.feedburner.com/fastcompany/headlines
  - http://www.newyorker.com/services/rss/feeds/everything.xml
  - http://economix.blogs.nytimes.com/feed/
  - http://allthingsd.com/feed/
  - http://feeds.feedburner.com/bigthink/main
  - http://smarthistory.khanacademy.org/rss
  - http://www.fastcodesign.com/rss.xml
  - http://artdaily.org/rss.asp
  - http://feeds.feedburner.com/RSSMicro/Top_News
  - http://www.google.com/trends/hottrends/atom/hourly
  - http://bits.blogs.nytimes.com/feed/
  - http://feeds.pinboard.in/rss/popular/wikipedia/
  - "http://en.wikipedia.org/w/api.php?action=featuredfeed&feed=featured&feedformat=atom"
  - http://waxy.org/links/index.xml
  - http://rss.cnn.com/rss/edition.rss
  - http://feeds.feedburner.com/flavorwire-rss
  - http://www.collaborativeconsumption.com/atom.xml
  - "http://news.google.com/news?pz=1&cf=all&ned=uk&hl=en&topic=h&num=3&output=rss"
  - http://feeds.feedburner.com/mcsweeneys
  - http://www.edidomus.it/ed/feedyn/feed.cfm?name=domus_english
  - http://www.scottaaronson.com/blog/?feed=rss2
  - http://feeds.ribbonfarm.com/Ribbonfarm?format=xml
  - http://www.ediblegeography.com/feed/
  - http://natgeofound.tumblr.com/rss
  - http://inpossibleme.weebly.com/1/feed
