urls:
  - http://www.vice.com/en_uk/rss
  - http://hypem.com/feed/popular/3day/1/feed.xml
  - http://feeds2.feedburner.com/slashfilm
  - http://feeds.boingboing.net/boingboing/iBag
  - http://weirdios.tumblr.com/rss
  - http://roxyintransit.tumblr.com/rss
  - http://feeds.feedburner.com/zenpencils
