urls:
  - http://roadsandkingdoms.com/feed/
  - http://www.theundscvrd.com/feed/
  - http://www.theguardian.com/theobserver/observer-tech-monthly/rss
  - "https://twitrss.me/twitter_user_to_rss/?user=70sscifiart"
  - http://www.fsgworkinprogress.com/feed/
  - http://titansgraverpg.tumblr.com/rss
  - http://thelostbyway.com/feed
  - http://www.vice.com/en_uk/rss
  - http://feeds2.feedburner.com/poorgirleatswell/cRhe
  - "http://createfeed.fivefilters.org/extract.php?url=capwatkins.com%2Flinks%2F&in_id_or_class=&url_contains="
  - http://www.theguardian.com/stage/theatre/rss
  - http://www.vice.com/en_uk/rss
  - http://hypem.com/feed/popular/3day/1/feed.xml
  - http://feeds2.feedburner.com/slashfilm
  - http://feeds.boingboing.net/boingboing/iBag
  - http://weirdios.tumblr.com/rss
  - http://feeds.feedburner.com/zenpencils
  - http://impeccabletablemanners.theguyliner.com/feed/
  - http://www.holidaypirates.com/feed
  - http://www.4newswall.com/rss
  - http://exystence.net/feed/
  - http://weputachipinit.tumblr.com/rss
  - http://www.dictionaryofobscuresorrows.com/rss
  - https://www.somewhere.com/feed
