urls:
  - http://feeds2.feedburner.com/PitchforkFeatures
  - http://www.postsecret.com/feeds/posts/default?alt=rss
  - http://www.thisiswhyimbroke.com/feed
  - http://tvtropes.org/pmwiki/rss.xml
  - http://feeds.feedburner.com/uproxx/filmdrunk
  - http://blog.okcupid.com/index.php/feed/
  - http://catalogliving.net/rss
  - http://feeds.feedburner.com/getthefive/pWyz
  - http://feeds.feedburner.com/twistedsifter
  - http://feeds.feedburner.com/getaddictedto
  - http://feeds.feedburner.com/The99Percent
  - http://hellogiggles.com/feed
  - http://feeds2.feedburner.com/slashfilm
  - http://backend.deviantart.com/rss.xml?q=special%3Add
  - http://rss1.smashingmagazine.com/feed/
  - http://kellyoxford.tumblr.com/rss
  - http://www.buzzfeed.com/index.xml
  - http://www.4ad.com/news.rss
  - http://emmas.blogg.se/index.rss
  - http://feeds.pinboard.in/rss/popular/
