urls:
  - http://feeds2.feedburner.com/PitchforkFeatures
  - http://feeds.feedburner.com/uproxx/filmdrunk
  - http://feeds.feedburner.com/getthefive/pWyz
  - http://feeds.feedburner.com/twistedsifter
  - http://feeds.feedburner.com/getaddictedto
  - http://feeds.feedburner.com/The99Percent
  - http://feeds2.feedburner.com/slashfilm
  - http://rss1.smashingmagazine.com/feed/
  - http://kellyoxford.tumblr.com/rss
  - http://www.4ad.com/news.rss
  - http://mag.ma/mustwatch.rss
  - http://clarkesworldmagazine.com/feed/rss/
  - http://www.toucharcade.com/feed/
  - http://feeds.feedburner.com/devourfeed
  - http://www.topiama.com/rss
  - http://networkawesome.com/rss/shows
  - http://www.nowness.com/issue/syndicate?output=rss
