urls:
  - http://feeds2.feedburner.com/PitchforkFeatures
  - http://www.thisiswhyimbroke.com/feed
  - http://tvtropes.org/pmwiki/rss.xml
  - http://feeds.feedburner.com/uproxx/filmdrunk
  - http://catalogliving.net/rss
  - http://feeds.feedburner.com/getthefive/pWyz
  - http://feeds.feedburner.com/twistedsifter
  - http://feeds.feedburner.com/getaddictedto
  - http://feeds.feedburner.com/The99Percent
  - http://feeds2.feedburner.com/slashfilm
  - http://backend.deviantart.com/rss.xml?q=special%3Add
  - http://rss1.smashingmagazine.com/feed/
  - http://kellyoxford.tumblr.com/rss
  - http://www.buzzfeed.com/index.xml
  - http://www.4ad.com/news.rss
  - http://emmas.blogg.se/index.rss
  - http://www.bonappetit.com/services/rss/feeds/dishoftheday.xml
  - http://mag.ma/mustwatch.rss
  - http://feeds.feedburner.com/oatmealfeed
  - http://clarkesworldmagazine.com/feed/rss/
  - http://www.toucharcade.com/feed/
  - http://feeds.feedburner.com/devourfeed
  - http://www.topiama.com/rss
