urls:
  - http://noisey.vice.com/en_uk/rss
  - http://motherboard.vice.com/en_uk/rss?trk_source=motherboard
  - http://thecreatorsproject.vice.com/en_uk/rss
  - http://www.vice.com/en_uk/rss
  - https://broadly.vice.com/en_us/rss
  - http://feeds.feedburner.com/londonist/sBMe
  - http://marginalrevolution.com/marginalrevolution/category/books/feed
  - https://www.fatherly.com/feeds/feed.rss
  - http://macro.ycombinator.com/feed.xml
  - http://feeds.feedburner.com/weburbanist
  - http://roadsandkingdoms.com/feed/
  - http://www.theundscvrd.com/feed/
  - http://www.theguardian.com/theobserver/observer-tech-monthly/rss
  - "https://twitrss.me/twitter_user_to_rss/?user=70sscifiart"
  - http://www.fsgworkinprogress.com/feed/
  - http://thelostbyway.com/feed
  - http://www.vice.com/en_uk/rss
  - http://feeds2.feedburner.com/poorgirleatswell/cRhe
  - http://www.theguardian.com/stage/theatre/rss
  - http://hypem.com/feed/popular/3day/1/feed.xml
  - http://feeds2.feedburner.com/slashfilm
  - http://feeds.feedburner.com/zenpencils
  - http://impeccabletablemanners.theguyliner.com/feed/
  - http://www.holidaypirates.com/feed
  - http://www.4newswall.com/rss
  - http://exystence.net/feed/
  - http://www.dictionaryofobscuresorrows.com/rss
  - http://cmxhub.com/feed/
  - http://www.ursulakleguin.com/rss.xml
  - http://www.crummy.com/rss.xml
  - http://www.decompmagazine.com/feed.xml
  - http://quoratopstories.tumblr.com/rss
  - http://www.feeddude.com/feeds/1038284433863214737.rss
  - http://feeds.theguardian.com/theguardian/uk/culture/rss
  - http://rss.nytimes.com/services/xml/rss/nyt/Arts.xml
  - http://www.ayoungertheatre.com/feed/
  - "http://www.minimallyminimal.com/blog?format=rss"
  - http://www.gatesnotes.com/home/rss
  - "https://theconversation.com/articles.atom?language=en"
  - http://feeds.feedburner.com/uclb/FMME
  - http://feeds.feedburner.com/booktwo
  - http://grantland.com/features/feed/
  - http://feeds.feedburner.com/oreilly/radar/atom
  - http://hackingrambert.tumblr.com/rss
  - http://feeds.feedburner.com/motherjones/main
  - http://warpspire.com/feed/
  - "http://gdata.youtube.com/feeds/base/users/everyframeapainting/uploads?alt=rss&v=2&orderby=published&client=ytapi-youtube-profile"
  - http://itch.io/feed/featured.xml
  - http://natgeofound.tumblr.com/rss
